# do not change max_action_dim, max_state_dim, max_views
max_action_dim: 24
max_state_dim: 24
max_views: 3

data_groups:
  ##############################################################################
  # Your embodiment_name:
  #   your_dataset_name:
  #     path: /path/to/your/dataset
  #     view_map:
  #       image_1: observation.images.image_1
  #       image_2: observation.images.image_2
  #       image_3: observation.images.image_3
################################################################################




  # This is an example of how to configure the dataset path and view mapping for MetaWorld
  # metaworld_sawyer:
  #   Evo1_MetaWorld:
  #     path: /home/dell/code/lintao/Evo_1/Evo1_training_dataset/Evo1_MetaWorld
  #     view_map:
  #       image_1: observation.images.image



  # This is an example of how to configure multi-task training for LIBERO.
  # The libero dataset is from https://huggingface.co/collections/IPEC-COMMUNITY/libero-benchmark-dataset

  # libero_franka:
  #   libero_spatial_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_spatial_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image

  #   libero_object_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_object_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image

  #   libero_goal_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_goal_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image

  #   libero_10_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_10_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image







  # This is an example of how to configure the dataset path and view mapping for RoboTwin

  # robotwin_robot:
  # click_alarmclock_v2.1:
  #   path: /share/taolin/datasets/robotwin/click_alarmclock_v2.1
  #   view_map:
  #     image_1: observation.images.image_1
  #     image_2: observation.images.image_2
  #     image_3: observation.images.image_3



  # R1Pro robot configuration for 2025 challenge dataset
  r1pro:
    challenge_task0006:
      path: /workspace/2025-challenge-demos/data/task-0006
      view_map:
        image_1: observation.images.rgb.head
        image_2: observation.images.rgb.left_wrist
        image_3: observation.images.rgb.right_wrist
      # Selected state features (24 dims total):
      # Left arm joint positions: 158-164 (7)
      # Right arm joint positions: 197-203 (7)
      # Left gripper position: 193-194 (2)
      # Right gripper position: 232-233 (2)
      # Trunk position: 236-239 (4)
      # Trunk velocity (first 2): 240-241 (2)
      state_indices: [158, 159, 160, 161, 162, 163, 164, 193, 194, 197, 198, 199, 200, 201, 202, 203, 232, 233, 236, 237, 238, 239, 240, 241]
